In [3]:
import tensorflow as tf

In [9]:
mnist = tf.keras.datasets.mnist

In [10]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [11]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [12]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [13]:
predictions = model(x_train[:1]).numpy()


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



In [14]:
predictions

array([[ 0.07552875, -0.03254195,  0.93494403,  0.14503057, -0.14682017,
        -0.5704002 ,  0.40678027, -0.66913646,  0.62854695,  0.23929712]],
      dtype=float32)

In [15]:
tf.nn.softmax(predictions).numpy()

array([[0.08741132, 0.07845727, 0.20644625, 0.09370266, 0.06998464,
        0.04581887, 0.12173861, 0.04151105, 0.1519639 , 0.10296541]],
      dtype=float32)

In [16]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [17]:
loss_fn(y_train[:1], predictions).numpy()

3.0830593

In [18]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [19]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 5s 89us/sample - loss: 0.3002 - accuracy: 0.9129
Epoch 2/5
60000/60000 [==============================] - 5s 83us/sample - loss: 0.1473 - accuracy: 0.9570
Epoch 3/5
60000/60000 [==============================] - 5s 80us/sample - loss: 0.1084 - accuracy: 0.9675
Epoch 4/5
60000/60000 [==============================] - 5s 81us/sample - loss: 0.0873 - accuracy: 0.9733
Epoch 5/5
60000/60000 [==============================] - 5s 81us/sample - loss: 0.0730 - accuracy: 0.9772


In [20]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 1s - loss: 0.0754 - accuracy: 0.9770


[0.07540731033165939, 0.977]

In [21]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [22]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.83278573e-09, 9.09384679e-10, 6.27383315e-07, 2.62217480e-04,
        1.22807201e-12, 3.49448612e-07, 1.55824220e-13, 9.99721229e-01,
        8.95967275e-07, 1.46255115e-05],
       [5.08332914e-06, 2.72059224e-05, 9.99933720e-01, 2.76959581e-05,
        2.59508686e-14, 4.72871761e-06, 1.46477510e-06, 3.21830019e-13,
        1.43253331e-07, 3.75390040e-13],
       [2.16494186e-06, 9.99024272e-01, 7.51902699e-05, 8.49501375e-05,
        4.78469265e-05, 7.38227436e-06, 3.34625729e-05, 6.06539834e-04,
        1.15471157e-04, 2.79811798e-06],
       [9.99653459e-01, 2.01090589e-09, 2.50294252e-05, 7.06717583e-06,
        6.96299594e-07, 5.35604777e-05, 2.31832193e-04, 1.61646494e-05,
        3.45845422e-07, 1.19310971e-05],
       [5.56120312e-06, 8.71731398e-09, 2.91090259e-06, 2.46375350e-07,
        9.89339888e-01, 5.26946087e-06, 1.09523387e-06, 3.43384672e-05,
        2.02210700e-07, 1.06104696e-02]], dtype=float32)>