In [43]:
import gym
import numpy as np 

In [44]:
# 1. Load Environment and Q-table structure
env = gym.make('FrozenLake8x8-v0')
Q = np.zeros([env.observation_space.n,env.action_space.n])
# env.obeservation.n, env.action_space.n gives number of states and action in env loaded

In [45]:
# 2. Parameters of Q-leanring
eta = .628
gma = .9
epis = 5000
rev_list = [] # rewards per episode calculate

In [48]:
# 3. Q-learning Algorithm
for i in range(epis):
    # Reset environment
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        #env.render()
        j+=1
        # Choose action from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state & reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + eta*(r + gma*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rev_list.append(rAll)
    #env.render()

In [49]:
print ("Reward Sum on all episodes " + str(sum(rev_list)/epis))
print ("Final Values Q-Table")
print (Q)

Reward Sum on all episodes 0.7738
Final Values Q-Table
[[1.04988552e-03 1.41445345e-03 4.39798479e-03 2.07175743e-03]
 [1.09387580e-03 1.83117673e-03 5.46018025e-03 1.78603015e-03]
 [1.47506262e-03 1.95620776e-03 8.80615046e-03 1.74694476e-03]
 [2.17667932e-03 2.38160881e-03 9.94825893e-03 2.98326938e-03]
 [2.42359220e-03 2.90482061e-03 1.51037584e-02 3.55963065e-03]
 [3.15057224e-03 4.04058788e-03 2.20588253e-02 3.15132179e-03]
 [4.22277450e-03 3.76016207e-03 2.37490455e-02 4.28787590e-03]
 [4.68826098e-03 2.99241585e-02 4.48012100e-03 4.60651809e-03]
 [1.25236025e-03 1.19802686e-03 1.16348737e-03 3.95805456e-03]
 [1.01180133e-03 9.36672513e-04 1.66522951e-03 5.07955864e-03]
 [1.17230492e-03 1.54627263e-03 1.02610590e-03 4.41399344e-03]
 [1.60152307e-04 1.58771311e-03 7.72787225e-04 1.13010517e-02]
 [1.63615073e-03 1.66652779e-03 2.29335933e-03 2.40755051e-02]
 [3.05060050e-03 3.45751558e-03 1.90609376e-02 2.62443765e-03]
 [4.53526309e-03 3.34988997e-02 5.04466040e-03 4.16969905e-03]


In [50]:
# Reset environment
s = env.reset()
d = False
# The Q-Table learning algorithm
while d != True:
    #env.render()
    # Choose action from Q table
    a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
    #Get new state & reward from environment
    s1,r,d,_ = env.step(a)
    #Update Q-Table with new knowledge
    Q[s,a] = Q[s,a] + eta*(r + gma*np.max(Q[s1,:]) - Q[s,a])
    s = s1
# Code will stop at d == True, and render one state before it

In [51]:
print ("Reward Sum on all episodes " + str(sum(rev_list)/epis))
print ("Final Values Q-Table")
print (Q)

Reward Sum on all episodes 0.7738
Final Values Q-Table
[[1.04988552e-03 1.41445345e-03 4.72214422e-03 2.07175743e-03]
 [1.09387580e-03 1.83117673e-03 7.52037081e-03 1.78603015e-03]
 [1.47506262e-03 1.95620776e-03 9.60796371e-03 1.74694476e-03]
 [2.17667932e-03 2.38160881e-03 1.50519059e-02 2.98326938e-03]
 [2.42359220e-03 2.90482061e-03 1.93654716e-02 3.55963065e-03]
 [3.15057224e-03 4.04058788e-03 1.89791249e-02 3.15132179e-03]
 [4.22277450e-03 3.76016207e-03 2.44230805e-02 4.28787590e-03]
 [4.68826098e-03 1.90783106e-02 4.48012100e-03 4.60651809e-03]
 [1.25236025e-03 1.19802686e-03 1.16348737e-03 3.95805456e-03]
 [1.01180133e-03 9.36672513e-04 1.66522951e-03 5.85075666e-03]
 [1.17230492e-03 1.54627263e-03 1.02610590e-03 4.51297210e-03]
 [1.60152307e-04 1.58771311e-03 7.72787225e-04 6.17974266e-03]
 [1.63615073e-03 1.66652779e-03 2.29335933e-03 1.45548399e-02]
 [3.05060050e-03 3.45751558e-03 2.53250446e-02 2.62443765e-03]
 [4.53526309e-03 2.44094680e-02 5.04466040e-03 4.16969905e-03]
